name: Cypress Tests

on: 
  workflow_dispatch:
    inputs:
      logLevel:
        required: false
        description: 'Some Description which goest to log'
        default: 'no message'
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main
      
jobs:
  test_run:
    name: Test run
    runs-on: ubuntu-latest
    env:
      TZ: America/Los_Angeles
    steps:
    - name: Checkout           
      uses: actions/checkout@v4.2.0

    - name: Run Cypress Tests
      uses: cypress-io/github-action@v6.7.6
      with:
        browser: chrome
    - name: Upload screenshots
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: cypress-screenshots
        path: cypress/screenshots/*